Karma/Models/Charity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Karma.Models
{
    public class Charity
    {
        public static readonly string ImagesDirName = Path.Combine("data", "CharityImages");

        public event EventHandler<CharityStateChangedEventArgs> CharityStateChanged;

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Display(Name = "Image")]
        public string ImagePath { get; set; }
        [Required]
        [MaxLength(120)]
        public string Description { get; set; }
        [NotMapped]
        [Display(Name = "Charity addresses")]
        public List<CharityAddress> CharityAddresses { get; set; }
        [NotMapped]
        [Display(Name = "Item types")]
        public List<CharityItemType> CharityItemTypes { get; set; }
        [Required]
        [Display(Name = "Request date")]
        public DateTime DateCreated { get; set; }
        [Required]
        [Display(Name = "Review state")]
        private Enums.ReviewState _reviewState;
        [Required]
        [Display(Name = "Review state")]
        public Enums.ReviewState ReviewState
        {
            get => _reviewState;
            set
            {
                if (value != _reviewState)
                {
                    _reviewState = value;

                    var args = new CharityStateChangedEventArgs();
                    args.CharityId = this.Id;
                    args.ReviewState = this.ReviewState;
                    args.TimeChanged = DateTime.UtcNow;

                    OnCharityStateChanged(args);
                }
            }
        }

        public Charity()
        {
            CharityAddresses = new List<CharityAddress>();
            CharityItemTypes = new List<CharityItemType>();
        }

        public static List<Charity> GetApprovedCharities(List<Charity> charities)
        {
            List<Charity> filtered = new List<Charity>();
            if (charities == null)
                return filtered;

            foreach (Charity c in charities)
            {
                if (c.ReviewState == Enums.ReviewState.Approved)
                {
                    filtered.Add(c);
                }
            }
            return filtered;
        }

        public static List<Charity> FilteredCharities(List<Charity> charities, ItemType itemType)
        {
            List<Charity> filtered = new List<Charity>();
            if (charities == null)
                return filtered;

            foreach (Charity c in charities)
            {
                var itemTypes = c.GetItemTypes();

                if (c.ReviewState == Enums.ReviewState.Approved
                    && itemTypes.Contains(itemType))
                {
                    filtered.Add(c);
                }
            }

            return filtered;
        }

        public List<ItemType> GetItemTypes()
        {
            var itemTypes = new List<ItemType>();
            itemTypes = CharityItemTypes.Select(x => x.ItemType).ToList();

            return itemTypes;
        }

        protected void OnCharityStateChanged(CharityStateChangedEventArgs e)
        {
            EventHandler<CharityStateChangedEventArgs> handler = CharityStateChanged;
            handler?.Invoke(this, e);
        }

    }

    public class CharityStateChangedEventArgs : EventArgs
    {
        public int CharityId { get; set; }
        public Enums.ReviewState ReviewState { get; set; }
        public DateTime TimeChanged { get; set; }
    }
}

Karma/Controllers/CharitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Karma.Data;
using Karma.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Geocoding;
using Geocoding.Google;
using Microsoft.Extensions.Configuration;

namespace Karma.Controllers
{
    public class CharitiesController : Controller
    {
        private readonly KarmaContext _context;

        private readonly IWebHostEnvironment _iWebHostEnv;

        private readonly GoogleMaps _googleMaps;

        private List<Charity> _charities;

        // Passes an object of type IWebHostEnvironment that carries information about our host environment.
        public CharitiesController(KarmaContext context, IWebHostEnvironment webHostEnvironment, GoogleMaps googleMaps)
        {
            _context = context;
            _iWebHostEnv = webHostEnvironment;
            _googleMaps = googleMaps;

            _charities = GetCharityList().Result;
        }

        // GET: Charities
        public async Task<IActionResult> Index()
        {
            return View(_charities);
        }

        [HttpGet]
        public IActionResult FilteredCharities(int itemTypeId)
        {
            List<Charity> filtered;
            if (itemTypeId < 0)
            {
                ViewBag.ItemType = null;
                filtered = Charity.GetApprovedCharities(_charities);
            }
            else
            {
                ItemType itemType = new ItemTypes()[itemTypeId];
                ViewBag.ItemType = itemType.Name;
                filtered = Charity.FilteredCharities(_charities, itemType);
            }
            return View(filtered);
        }

        // GET: Charities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charity == null)
            {
                return NotFound();
            }

            var charityAddresses = GetCharityLocales(charity).Result;
            ViewBag.CharityAddresses = charityAddresses;

            return View(charity);
        }

        public async Task<List<Address>> GetCharityLocales(Charity charity)
        {
            List<Address> addresses = new List<Address>();
            List<CharityAddress> charityAddresses = GetCharityAddresses(charity).Result;
            string serviceApiKey = _googleMaps.ServiceApiKey;

            if (serviceApiKey != null)
            {
                ViewBag.ApiKey = serviceApiKey; 
                GoogleGeocoder geocoder = new GoogleGeocoder(serviceApiKey);

                foreach (CharityAddress address in charityAddresses)
                {
                    string fullAddress = address.GetFullAddress();
                    IEnumerable<GoogleAddress> googleAddress = await geocoder.GeocodeAsync(fullAddress);
                    GoogleAddress first = googleAddress.FirstOrDefault();

                    if(first != null)
                        addresses.Add(first);
                }
            }

            return addresses;
        }

        // GET: Charities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Charities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Address,ItemTypes,ImagePath,Description")] CreateCharityViewModel charityForm, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                Charity charity = new();

                if (CopyFileToRoot(charity, file) == false)
                {
                    return View(charity);
                }

                FillCharityDetails(charity, charityForm);
                _context.Add(charity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(charityForm);
        }

        private void FillCharityDetails(Charity charity, CreateCharityViewModel charityForm)
        {
            charity.Description = charityForm.Description;
            charity.Name = charityForm.Name;
            charity.DateCreated = DateTime.UtcNow;
            charity.ReviewState = Enums.ReviewState.Waiting;
        }

        // GET: Charities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity.FindAsync(id);
            if (charity == null)
            {
                return NotFound();
            }
            return View(charity);
        }

        // POST: Charities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ImagePath,Description,DateCreated,ReviewState")] Charity charity, IFormFile file)
        {
            if (id != charity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // If the edited charity is identical to the old one
                var dbCharity =  _context.Charity.Find(charity.Id);

                if(file == null)
                    charity.ImagePath = dbCharity.ImagePath;
                
                _context.Entry(dbCharity).State = EntityState.Detached;

                if (CopyFileToRoot(charity, file) == false)
                {
                    return View(charity);
                }

                try
                {
                    _context.Update(charity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharityExists(charity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "CharityManager");
            }
            return View(charity);
        }

        // GET: Charities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charity == null)
            {
                return NotFound();
            }

            return View(charity);
        }

        // POST: Charities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var charity = await _context.Charity.FindAsync(id);
            _context.Charity.Remove(charity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CharityExists(int id)
        {
            return _context.Charity.Any(e => e.Id == id);
        }

        public async Task<List<Charity>> GetCharityList()
        {
            List<Charity> charities = await _context.Charity.ToListAsync();

            foreach (var charity in charities)
            {
                charity.CharityItemTypes = GetCharityItemTypes(charity).Result;
                charity.CharityAddresses = GetCharityAddresses(charity).Result;
            }

            return charities;
        }

        public async Task<List<CharityItemType>> GetCharityItemTypes(Charity charity)
        {
            var charityItemTypesList = await _context.CharityItemType
                .Where(x => x.CharityId == charity.Id)
                .ToListAsync();

            return charityItemTypesList;
        }

        public async Task<List<CharityAddress>> GetCharityAddresses(Charity charity)
        {
            var charityAddressesList = await _context.CharityAddress
                .Where(x => x.CharityId == charity.Id)
                .OrderBy(m => m.Country)
                .ThenBy(m => m.City)
                .ToListAsync();

            return charityAddressesList;
        }

        // Returns null if there is no file, false if extension is invalid and true otherwise
        private bool? IsValidFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                return null;
            }
            else if (!Path.GetExtension(file.FileName).IsValidExtension())
            {
                return false;
            }
            return true;
        }

        private bool CopyFileToRoot(Charity charity, IFormFile file, string ext = null)
        {
            bool? isValidFile = IsValidFile(file);
            if (isValidFile == false)
            {
                ViewBag.Message = "Invalid file type.";
                return false;
            }
            else if (isValidFile == true)
            {
                ext = ext ?? Path.GetExtension(file.FileName);

                string fileName = "x" + DateTime.Now.Ticks.ToString() + ext;

                string path = Path.Combine(_iWebHostEnv.WebRootPath, Charity.ImagesDirName, fileName);

                // Copying file to wwwroot/CharityImages

Karma/Views/Charities/Create.cshtml
@model Karma.Models.CreateCharityViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Charity</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <textarea asp-for="Description" class="form-control" rows="6"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemTypes" class="control-label">Category</label>
                <select asp-for="ItemTypes" id="multi-select" class="form-control" multiple
                        asp-items='@new SelectList(ItemTypes.Types, "Key", "Value")'>
                </select>
                <span asp-validation-for="ItemTypes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label">Upload charity logo</label>
                <input type="file" class="form-control-file" accept=".jpg, .jpeg, .png, .bmp" name="file" />
                <span class="text-danger">@ViewBag.Message</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Karma/Views/Charities/Delete.cshtml
@model Karma.Models.Charity

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Charity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Karma/Views/Charities/Details.cshtml
@using Geocoding;

@model Karma.Models.Charity

@{
    ViewData["Title"] = "Details";
    var charityItemTypes = Model.GetItemTypes();
    var charityAddresses = (List<Address>)ViewBag.CharityAddresses;

    double lat = 0;
    double lng = 0;
    if (charityAddresses.Any())
    {
        lat = charityAddresses.First().Coordinates.Latitude;
        lng = charityAddresses.First().Coordinates.Longitude;
    }

    var googleApi = "https://maps.googleapis.com/maps/api/js?key=" + (string) ViewBag.ApiKey;
}

<head>
    <script src=@googleApi></script>
</head>

<h1>@Model.Name</h1>

<body onload="loadMap(@lat, @lng)">
    <div class="container">
        <div class="row align-content-between">
            <div class="col col-12 col-sm-12 col-md-12 col-lg-5 mb-4">
                <h5>
                    @if (charityItemTypes.Any())
                    {
                        foreach (var itemType in Model.CharityItemTypes)
                        {
                            <span class="badge badge-pill badge-info">@itemType.ItemType.Name</span>
                        }
                    }
                </h5>
                <hr />
                @if (Model.ImagePath != null && Model.ImagePath != "")
                {
                    <img src="/@Charity.ImagesDirName/@Model.ImagePath" asp-append-version="true"
                         alt="Item image" class="img-fluid" style="max-width:400px;" />
                    <br />
                }
            </div>
            <div class="col col-12 col-sm-12 col-md-12 col-lg-6">
                @if (charityAddresses.Any())
                {
                    <h5 class="mb-4">Where can you find the charity?</h5>
                    <ul class="list-group">
                        @foreach (var address in charityAddresses)
                        {
                            <li class="list-group-item" lat=@address.Coordinates.Latitude
                                lng="@address.Coordinates.Longitude">@address.FormattedAddress</li>
                            }
                    </ul>
                    <div id="map" class="mt-4" style="width:500px; height:400px;"></div>
                }
                else if (Model.CharityAddresses.Any())
                {
                    <h5 class="mb-4">Where can you find the charity?</h5>
                    <ul class="list-group">
                        @foreach (var address in Model.CharityAddresses)
                        {
                            <li class="list-group-item">@address.GetFullAddress()</li>
                        }
                    </ul>
                }
                else
                {
                    <h5>We're sorry, the charity hasn't provided their location</h5><hr />
                }
            </div>
        </div>
    </div>
</body>

<script>
    $(function () {
        $('.list-group li').click(function (e) {
            e.preventDefault();
            $that = $(this);
            $that.parent().find('li').removeClass('active');
            $that.addClass('active');

            var lat = this.attributes.lat.value;
            var lng = this.attributes.lng.value;
            loadMap(lat, lng);
        })
    });

    function loadMap(lat, lng) {
        if (lat != 0 && lng != 0) {
            var mapOptions = {
                center: new google.maps.LatLng(lat, lng),
                zoom: 10
            }

            var map = new google.maps.Map(document.getElementById("map"), mapOptions);

            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(lat, lng),
                map: map,
            });
        }
    }

</script>

Karma/Views/Charities/DetailsForCharityManager.cshtml
@model Karma.Models.Charity

@{
    ViewData["Title"] = "Details";
    var charityItemTypes = Model.GetItemTypes();
}


<h1>
    @Model.Name
<span class="badge @(Model.ReviewState == Enums.ReviewState.Approved? "badge-success" : "badge-secondary") mb-3">
    @Html.DisplayFor(model => model.ReviewState)
</span>
</h1>

<div>
    <h5>
        @if (charityItemTypes.Any())
        {
            foreach (var itemType in Model.CharityItemTypes)
            {
                <span class="badge badge-pill badge-info">@itemType.ItemType.Name</span>
            }
        }
    </h5>
    <hr />
    @if (Model.ImagePath != null && Model.ImagePath != "")
    {
        <img src="/@Charity.ImagesDirName/@Model.ImagePath" asp-append-version="true"
             alt="Item image" class="img-fluid" style="max-width:400px;" />
        <br />
    }
</div>
<hr />
<div>
    Posted at @Html.DisplayFor(model => model.DateCreated)
</div>

Karma/Views/Charities/Edit.cshtml
@model Karma.Models.Charity

@{
    ViewData["Title"] = "Edit";
}

<br />
<div class="row justify-content-between">
    <div class="col-md-5">
        <form asp-controller="Charities" asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateCreated" />
            <input type="hidden" asp-for="ReviewState" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="6"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label">Upload charity logo</label>
                <input type="file" class="form-control-file" accept=".jpg, .jpeg, .png, .bmp" name="file" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <partial name="~/Views/Charities/DetailsForCharityManager.cshtml" for="@Model" />
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Karma/Views/Charities/FilteredCharities.cshtml
@model IEnumerable<Karma.Models.Charity>


@{
    Layout = null;
}

@if ((Model == null || !Model.Any()) && ViewBag.ItemType != null)
{
    <h3>We're sorry, there are no charities with tag <span class="badge badge-primary">@ViewBag.ItemType</span></h3>
}
else if (ViewBag.ItemType != null)
{
    <h3>Charities with tag <span class="badge badge-primary">@ViewBag.ItemType</span></h3>
}
<div class="post-cards container-fluid content-row">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col col-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card h-100">
                    @if (item.ImagePath != null && item.ImagePath != "")
                    {
                        <img class="card-img-top ratio ratio-4x3" src="/@Charity.ImagesDirName/@item.ImagePath" asp-append-version="true" alt="" 
                             style="max-height:300px; object-fit: cover;">
                    }
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(m => item.Name)</h5>
                        <p class="card-text">@Html.DisplayFor(model => item.Description)</p>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">View details</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Karma/Views/Charities/Index.cshtml
@model IEnumerable<Karma.Models.Charity>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Karma/Views/Charities/Review.cshtml
@model Karma.Models.Charity

@{
    ViewData["Title"] = "Review";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <h3>You have currently reviewed all the charity reviewal requests.</h3>
}
else
{
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-4">
                <p>@ViewBag.oldReview</p>
                <p>@ViewBag.newReview</p>
            </div>
        </div>
    </div>
    

    <h1>Review</h1>

    <div>
        <h4>Charity reviewal requests</h4>
        <hr />
        <form asp-action="Review">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.AddressesPath)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.AddressesPath)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ItemTypePath)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ItemTypePath)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ImagePath)
                </dt>
                <dd class="col-sm-10">
                    @if (Model.ImagePath != null && Model.ImagePath != "")
                    {
                        <img src="/@Charity.ImagesDirName/@Model.ImagePath" asp-append-version="true"
                             alt="Item image" class="img-fluid" style="max-width:400px;" />
                    }
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.DateCreated)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.DateCreated)
                </dd>
            </dl>
            <div class="form-group">
                <label asp-for="ReviewState" class="control-label">Review state</label>
                <select asp-for="ReviewState" class="form-control"
                        asp-items="Html.GetEnumSelectList<Enums.ReviewState>()">
                    <option>Select...</option>
                </select>
                <span asp-validation-for="ReviewState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
}



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}