Karma/Controllers/CharityItemTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Karma.Data;
using Karma.Models;

namespace Karma
{
    public class CharityItemTypesController : Controller
    {
        private readonly KarmaContext _context;

        public CharityItemTypesController(KarmaContext context)
        {
            _context = context;
        }

        // GET: CharityItemTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.CharityItemType.ToListAsync());
        }

        // GET: CharityItemTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityItemType = await _context.CharityItemType
                .FirstOrDefaultAsync(m => m.CharityId == id);
            if (charityItemType == null)
            {
                return NotFound();
            }

            return View(charityItemType);
        }

        // GET: CharityItemTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CharityItemTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CharityId,ItemTypeId")] CharityItemType charityItemType)
        {
            var charityItemTypeExists = await _context.CharityItemType
                .Where(m => m.CharityId == charityItemType.CharityId 
                    && m.ItemTypeId == charityItemType.ItemType.Id)
                .FirstOrDefaultAsync();

            if (charityItemTypeExists != null)
            {
                ModelState.AddModelError("ItemTypeExists", "This category has already been added");
                return View(charityItemType);
            }

            if (ModelState.IsValid)
            {
                _context.Add(charityItemType);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "CharityManager");
            }
            return View(charityItemType);
        }

        // GET: CharityItemTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityItemType = await _context.CharityItemType.FindAsync(id);
            if (charityItemType == null)
            {
                return NotFound();
            }
            return View(charityItemType);
        }

        // POST: CharityItemTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CharityId,ItemTypeId")] CharityItemType charityItemType)
        {
            if (id != charityItemType.CharityId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(charityItemType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharityItemTypeExists(charityItemType.CharityId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "CharityManager");
            }
            return View(charityItemType);
        }

        // GET: CharityItemTypes/Delete/5
        public async Task<IActionResult> Delete(int? charityId, int? itemTypeId)
        {
            if (charityId == null || itemTypeId == null)
            {
                return NotFound();
            }

            var charityItemType = await _context.CharityItemType
                .FirstOrDefaultAsync(m => m.CharityId == charityId && m.ItemTypeId == itemTypeId);
            if (charityItemType == null)
            {
                return NotFound();
            }

            return View(charityItemType);
        }

        // POST: CharityItemTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int charityId, int itemTypeId)
        {
            var charityItemType = await _context.CharityItemType
                .FirstOrDefaultAsync(m => m.CharityId == charityId && m.ItemTypeId == itemTypeId);
            _context.CharityItemType.Remove(charityItemType);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "CharityManager");
        }

        private bool CharityItemTypeExists(int id)
        {
            return _context.CharityItemType.Any(e => e.CharityId == id);
        }

    }
}

Karma/Views/CharityItemTypes/Create.cshtml
@model Karma.Models.CharityItemType

@{
    ViewData["Title"] = "Create";
}

<h5>Add a category</h5>
<br />
<form asp-controller="CharityItemTypes" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CharityId" />
    <div class="form-group">
        <label asp-for="ItemTypeId" class="control-label">Category</label>
        <select asp-for="ItemTypeId" class="form-control"
                asp-items='@new SelectList(ItemTypes.Types, "Key", "Value")'>
            <option value="-1">Select...</option>
        </select>
        <span asp-validation-for="ItemTypeId" class="text-danger"></span>
        <span class="text-danger">@Html.ValidationMessage("ItemTypeExists")</span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
</form>

Karma/Views/CharityItemTypes/Delete.cshtml
@model Karma.Models.CharityItemType

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ItemType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ItemType.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CharityId" />
        <input type="hidden" asp-for="ItemTypeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="CharityManager" asp-action="Index">Back to List</a>
    </form>
</div>

Karma/Views/CharityItemTypes/Details.cshtml
@model Karma.Models.CharityItemType

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>CharityItemType</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Karma/Views/CharityItemTypes/Edit.cshtml
@model Karma.Models.CharityItemType

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>CharityItemType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CharityId" />
            <input type="hidden" asp-for="ItemTypeId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Karma/Views/CharityItemTypes/Index.cshtml
@using Karma.Models 

@model IEnumerable<Karma.Models.CharityItemType>

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemType)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.ItemType.Name
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "CharityItemTypes", new { charityId = item.CharityId, itemTypeId = item.ItemTypeId })
            </td>
        </tr>
}
    </tbody>
</table>