Karma/Controllers/CharityAddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Karma.Data;
using Karma.Models;

namespace Karma
{
    public class CharityAddressesController : Controller
    {
        private readonly KarmaContext _context;

        public CharityAddressesController(KarmaContext context)
        {
            _context = context;
        }

        // GET: CharityAddresses
        public async Task<IActionResult> Index()
        {
            return View(await _context.CharityAddress.ToListAsync());
        }

        // GET: CharityAddresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityAddress = await _context.CharityAddress
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charityAddress == null)
            {
                return NotFound();
            }

            return View(charityAddress);
        }

        // GET: CharityAddresses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CharityAddresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CharityId,Country,City,Street,HouseNumber,PostCode")] CharityAddress charityAddress)
        {
            if (ModelState.IsValid)
            {
                _context.Add(charityAddress);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","CharityManager");
            }
            return View(charityAddress);
        }

        // GET: CharityAddresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityAddress = await _context.CharityAddress.FindAsync(id);
            if (charityAddress == null)
            {
                return NotFound();
            }
            return View(charityAddress);
        }

        // POST: CharityAddresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CharityId,Country,City,Street,HouseNumber,PostCode")] CharityAddress charityAddress)
        {
            if (id != charityAddress.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(charityAddress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharityAddressExists(charityAddress.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "CharityManager");
            }
            return View(charityAddress);
        }

        // GET: CharityAddresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityAddress = await _context.CharityAddress
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charityAddress == null)
            {
                return NotFound();
            }

            return View(charityAddress);
        }

        // POST: CharityAddresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var charityAddress = await _context.CharityAddress.FindAsync(id);
            _context.CharityAddress.Remove(charityAddress);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "CharityManager");
        }

        private bool CharityAddressExists(int id)
        {
            return _context.CharityAddress.Any(e => e.Id == id);
        }
    }
}

Karma/Views/CharityAddresses/Create.cshtml
@model Karma.Models.CharityAddress

@{
    ViewData["Title"] = "Create";
}

<h5>Add a new address</h5>
<br />
<form asp-controller="CharityAddresses" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="CharityId" />
    <div class="form-group">
        <label asp-for="Country" class="control-label"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="City" class="control-label"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Street" class="control-label"></label>
        <input asp-for="Street" class="form-control" />
        <span asp-validation-for="Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="HouseNumber" class="control-label"></label>
        <input asp-for="HouseNumber" class="form-control" />
        <span asp-validation-for="HouseNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PostCode" class="control-label"></label>
        <input asp-for="PostCode" class="form-control" />
        <span asp-validation-for="PostCode" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
</form>

Karma/Views/CharityAddresses/Delete.cshtml
@model Karma.Models.CharityAddress

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HouseNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HouseNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="CharityManager" asp-action="Index">Back to List</a>
    </form>
</div>

Karma/Views/CharityAddresses/Details.cshtml
@model Karma.Models.CharityAddress

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>CharityAddress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CharityId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CharityId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HouseNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HouseNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Karma/Views/CharityAddresses/Edit.cshtml
@model Karma.Models.CharityAddress

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>CharityAddress</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CharityId" class="control-label"></label>
                <input asp-for="CharityId" class="form-control" />
                <span asp-validation-for="CharityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HouseNumber" class="control-label"></label>
                <input asp-for="HouseNumber" class="form-control" />
                <span asp-validation-for="HouseNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostCode" class="control-label"></label>
                <input asp-for="PostCode" class="form-control" />
                <span asp-validation-for="PostCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="CharityManager" asp-action="Index">Back to List</a>
</div>

Karma/Views/CharityAddresses/Index.cshtml
@model IEnumerable<Karma.Models.CharityAddress>

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HouseNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HouseNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostCode)
            </td>
            <td>
                <a asp-controller="CharityAddresses" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="CharityAddresses" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>